execute at @a run tp @a[tag=team1] @r[tag=team1]
execute at @a run tp @a[tag=team2] @r[tag=team2]
execute at @a run tp @a[tag=team3] @r[tag=team3]
execute at @a run tp @a[tag=team4] @r[tag=team4]
execute at @a run tp @a[tag=team5] @r[tag=team5]
execute at @a run tp @a[tag=team6] @r[tag=team6]
execute at @a run tp @a[tag=team7] @r[tag=team7]
execute at @a run tp @a[tag=team8] @r[tag=team8]